###
//create parent account
POST http://localhost:9010/parent-sign-up

{
    "phone":"9840453228"
}


###
//parent otp verify 
POST http://localhost:9010/parent-verify

{
    "phone":"9840453228",
    "otp":"994440"
}

###
//set parent password
POST http://localhost:9010/parent-set-password

{
    "phone":"9840453228",
    "password":"123456789"
}
 
### 
// Parent Login 
POST http://localhost:9010/parent-login

{
    "phone":"9840453228",
    "password":"123456789"
}

### 
// Add Parent name
POST http://localhost:9010/add-parent-detail
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRjMTQzY2E3LTAwYTktNDQ1ZS1hYzM5LTkwYTAwYjJlZTAwMyIsInVzZXJuYW1lIjoiIiwicGFyZW50X2lkIjo0LCJpc3N1ZWRfYXQiOiIyMDIyLTA5LTAyVDE1OjI5OjA0LjgwMDUyNTM3OSswNTo0NSIsImV4cGlyZWRfYXQiOiIyMDMyLTEyLTA4VDE1OjI5OjA0LjgwMDUyNzc1MyswNTo0NSJ9.YQMb_N96M9Q7ll4pxr5D1kkWJTFHEJ8UNEQLvFfopGo

{
    "full_name":"Nirpa Giri"
}

### 
// Edit Parent Details
PATCH http://localhost:9010/edit-parent-detail
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRjMTQzY2E3LTAwYTktNDQ1ZS1hYzM5LTkwYTAwYjJlZTAwMyIsInVzZXJuYW1lIjoiIiwicGFyZW50X2lkIjo0LCJpc3N1ZWRfYXQiOiIyMDIyLTA5LTAyVDE1OjI5OjA0LjgwMDUyNTM3OSswNTo0NSIsImV4cGlyZWRfYXQiOiIyMDMyLTEyLTA4VDE1OjI5OjA0LjgwMDUyNzc1MyswNTo0NSJ9.YQMb_N96M9Q7ll4pxr5D1kkWJTFHEJ8UNEQLvFfopGo

{
    "full_name":"Nirpa Raj Mallick",
    "address":"Dhangadhi"
}

###
//create parent account use in forget password or resend code function
POST http://localhost:9010/parent-resend-code

{
    "phone":"9840453228"
}

###
// Get Details of Children in Parent Profile 
GET http://localhost:9010/children-details
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImUwNzA4ZWUwLTVlZmYtNDM4My05YWJiLTVhZGY0MWYyYzg3MiIsInVzZXJuYW1lIjoiam9ja29sb2NrbyIsInBhcmVudF9pZCI6NTYsImlzc3VlZF9hdCI6IjIwMjEtMTItMjBUMDc6MzI6MDQuOTQ1OTc2MjY4WiIsImV4cGlyZWRfYXQiOiIyMDIxLTEyLTI0VDExOjMyOjA0Ljk0NTk3ODIxNVoifQ.igO2PGOGbSprQnF02hRsgnRWFiidB1Wh9PxmFj_2cxI


###
//Get parent Details 
GET http://localhost:9010/parent-detail

###
//Get child Details 
GET http://localhost:9010/child-detail

###
//Create Child Details
POST http://localhost:9010/add-child-detail
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk2ZmExOTVkLTk2ZTItNDY4Yy1hMzgzLWY1OTUzYmViZmE5MyIsInVzZXJuYW1lIjoiY2hvcmEiLCJwYXJlbnRfaWQiOjEsImlzc3VlZF9hdCI6IjIwMjEtMTItMTJUMDU6NTI6MjIuODM0MzE3MDY4WiIsImV4cGlyZWRfYXQiOiIyMDIxLTEyLTE2VDA5OjUyOjIyLjgzNDMxODU5NloifQ.jijyRMSiJH8nsqxG1qig7AR_Y7W1A0jIcJsRLMsBWAI

{
    "full_name":"Mero Chora",
	"date_of_birth":"2021-12-11",
	"gender":"Male",
    "school" :"Nandi",
	"country" :"Nepal",
	"state" :"state2"
}

###
//Update Child Details
PATCH  http://localhost:9010/edit-child-detail
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQzMzIxYjVkLTM4NDctNDM1NS04OTRkLWRkOGRlYzQ1MTVjMyIsInVzZXJuYW1lIjoiZHJ1bWtpbGxlciIsInBhcmVudF9pZCI6OCwiaXNzdWVkX2F0IjoiMjAyMS0xMi0yOFQwODozNTo0Ni43NDU4NTg0OTFaIiwiZXhwaXJlZF9hdCI6IjIwMzItMDQtMDRUMDg6MzU6NDYuNzQ1ODU5OTIxWiJ9.Rbj_Wyd07scuRAeUh1CFWPv3Rbq6kybj5-1H7huEXMU

{
    "full_name":"Messi",
	"gender":"Male",
    "school" :"LA school",
	"country" :"Nepal",
	"state" :"Province 2",
    "date_of_birth": "2015-06-15",
    "grade":5
}

### 
//get time table 0f their own child 
POST http://localhost:9010/get-time-table-parent
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMyYzNkYWFiLTQzNzQtNDBiNi1hZTYxLWQwMDkzMDU2NTY1NCIsInVzZXJuYW1lIjoiSSBhbSB0aGUgZG9uIiwicGFyZW50X2lkIjoyNSwiaXNzdWVkX2F0IjoiMjAyMS0xMi0yNlQwODozMTowMC4xMzg1NDY2MThaIiwiZXhwaXJlZF9hdCI6IjIwMzItMDQtMDJUMDg6MzE6MDAuMTM4NTQ4NDE3WiJ9.TsMf1Uq00gwmLIpLB_GJGzKtfjCwRgCccCpzT9rm90A

{
    "child_id":1
}

### 
// child login
POST http://localhost:9010/child-login

{
    "username":"chora",
    "password":"nanditech"
}


//Payment system 
###
//Khalti 
//khalti one or first api
POST http://localhost:9010/payment/khalti/one
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OTAxYjQwLTA1NzQtNDkwYi05YzRkLWZjNGMyZmQyOGU2MyIsInVzZXJuYW1lIjoiIiwicGFyZW50X2lkIjoxMiwiaXNzdWVkX2F0IjoiMjAyMS0xMi0wNlQxNDo1OToxNS43MjQzNTczODcrMDU6NDUiLCJleHBpcmVkX2F0IjoiMjAyMS0xMi0xMFQxODo1OToxNS43MjQzNTc1NDMrMDU6NDUifQ.tXuGD-7alnLwsAtJTjzXwHJqBm9OpDwPN8Ho8wZ0dRs

{
    "public_key":"test_public_key_00c7a01504da4d7a9b836f41777bef9a",
    "mobile":"9844329569",
    "transaction_pin":"1712",
    "amount": 100000 ,
    "product_identity":"demo", 
    "product_name":"edtech" 
}

###
//khalti two or second api
POST http://localhost:9010/payment/khalti/two
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5YjQ3NmViLTE3MWMtNDE1YS1iM2IwLTJkMzU0YmE2ZTMwZCIsInVzZXJuYW1lIjoiQWFzaHUgTWFsbGljayIsInBhcmVudF9pZCI6MTIsImlzc3VlZF9hdCI6IjIwMjEtMTItMTVUMDg6MzU6NTguNjEyODU3MDI4WiIsImV4cGlyZWRfYXQiOiIyMDIxLTEyLTE5VDEyOjM1OjU4LjYxMjg1ODYxNFoifQ.j8WYyfNgREA2fwX-a5_hLxsQgBQovn6qNT6_EBklIaA

{ 
    "public_key":"test_public_key_00c7a01504da4d7a9b836f41777bef9a",
    "token":"n4wQnV3NmNyGaDgebckFTY",
    "confirmation_code":"989546", 
	"transaction_pin":"1712"
}
###
//khalti three or third api
POST http://localhost:9010/payment/khalti/three
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5YjQ3NmViLTE3MWMtNDE1YS1iM2IwLTJkMzU0YmE2ZTMwZCIsInVzZXJuYW1lIjoiQWFzaHUgTWFsbGljayIsInBhcmVudF9pZCI6MTIsImlzc3VlZF9hdCI6IjIwMjEtMTItMTVUMDg6MzU6NTguNjEyODU3MDI4WiIsImV4cGlyZWRfYXQiOiIyMDIxLTEyLTE5VDEyOjM1OjU4LjYxMjg1ODYxNFoifQ.j8WYyfNgREA2fwX-a5_hLxsQgBQovn6qNT6_EBklIaA

{
   "number" :"9844329569",
	"token" :"n4wQnV3NmNyGaDgebckFTY",
    "trid":"cQFKDB6D5wbatFfy45ZXkP",
	"amount" :100000,
	"childId" :[1,2],
    "save": false
}

// Dec 20 2021 
//video 
//fetch video by class
###
GET http://localhost:9010/video/class
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdiZjdhYjExLWQ3NWItNDE1Yi05M2ZlLWEzNDY4ZTc0NjU4NyIsInVzZXJuYW1lIjoiY2hvcmEiLCJwYXJlbnRfaWQiOjEsImlzc3VlZF9hdCI6IjIwMjEtMTItMjBUMDU6NDA6MTguNTk0MzIzNTAyWiIsImV4cGlyZWRfYXQiOiIyMDIxLTEyLTI0VDA5OjQwOjE4LjU5NDMyNTE3NVoifQ.cAImQomSK3Sh6yHA5zCxqNSLnf1ixTidqhJvZ0qRIio



// fetch video by subject
###
POST http://localhost:9010/video/subject
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdiZjdhYjExLWQ3NWItNDE1Yi05M2ZlLWEzNDY4ZTc0NjU4NyIsInVzZXJuYW1lIjoiY2hvcmEiLCJwYXJlbnRfaWQiOjEsImlzc3VlZF9hdCI6IjIwMjEtMTItMjBUMDU6NDA6MTguNTk0MzIzNTAyWiIsImV4cGlyZWRfYXQiOiIyMDIxLTEyLTI0VDA5OjQwOjE4LjU5NDMyNTE3NVoifQ.cAImQomSK3Sh6yHA5zCxqNSLnf1ixTidqhJvZ0qRIio

{   
    "subject":"SCIENCE"
}
// fetch video by id or fetch singel video
###
POST http://localhost:9010/video/single
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdiZjdhYjExLWQ3NWItNDE1Yi05M2ZlLWEzNDY4ZTc0NjU4NyIsInVzZXJuYW1lIjoiY2hvcmEiLCJwYXJlbnRfaWQiOjEsImlzc3VlZF9hdCI6IjIwMjEtMTItMjBUMDU6NDA6MTguNTk0MzIzNTAyWiIsImV4cGlyZWRfYXQiOiIyMDIxLTEyLTI0VDA5OjQwOjE4LjU5NDMyNTE3NVoifQ.cAImQomSK3Sh6yHA5zCxqNSLnf1ixTidqhJvZ0qRIio

{   "video_id":6
}

// add video
###
POST http://localhost:9010/video/add


{    "grade":6,
    "subject":"SCIENCE",
    "topic":"Magnetism",
    "url":"https://www.youtube.com/watch?v=hFAOXdXZ5TM&ab_channel=minutephysics"
}
###
//ADD payment by esewa or sdk 
POST http://localhost:9010/payment/sdk
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5YjQ3NmViLTE3MWMtNDE1YS1iM2IwLTJkMzU0YmE2ZTMwZCIsInVzZXJuYW1lIjoiQWFzaHUgTWFsbGljayIsInBhcmVudF9pZCI6MTIsImlzc3VlZF9hdCI6IjIwMjEtMTItMTVUMDg6MzU6NTguNjEyODU3MDI4WiIsImV4cGlyZWRfYXQiOiIyMDIxLTEyLTE5VDEyOjM1OjU4LjYxMjg1ODYxNFoifQ.j8WYyfNgREA2fwX-a5_hLxsQgBQovn6qNT6_EBklIaA

{
   "number" :"9844329569",
	"token" :"n4wQnV3NmNyGaDgebckFTY",
    "trid":"cQFKDB6D5wbatFfy45ZXkP",
	"amount" :100000,
	"childId" :[1,2],
    "save": false
}
###
//get payment details 
GET http://localhost:9010/payment/details
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5YjQ3NmViLTE3MWMtNDE1YS1iM2IwLTJkMzU0YmE2ZTMwZCIsInVzZXJuYW1lIjoiQWFzaHUgTWFsbGljayIsInBhcmVudF9pZCI6MTIsImlzc3VlZF9hdCI6IjIwMjEtMTItMTVUMDg6MzU6NTguNjEyODU3MDI4WiIsImV4cGlyZWRfYXQiOiIyMDIxLTEyLTE5VDEyOjM1OjU4LjYxMjg1ODYxNFoifQ.j8WYyfNgREA2fwX-a5_hLxsQgBQovn6qNT6_EBklIaA

###
GET https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=Xf_VZ8GxU1Y&ab_channel=Don%27tMemorise$&format=json